### ISSUE TITLE
monster id for ?

### ISSUE THREAD

**Issue by PatrickSR** [wwylele/mhrice#1]
I looked at the Hitzone data

Monster 001 == Rathian
Monster 060 == Arzuros
Monster 082 == Mizutsune
Monster 098 == Great Izuchi

Right?

**Comment by wwylele** [comment]
I would guess so, but I haven't found the monster name mapping data. Since we expect a larger amount of monsters for the full game, it isn't very meaningful to manually assign names for these 4 monsters for now...

**Comment by PatrickSR** [comment]
I see, thank you.
I developing an app about rise, very excited when I see this repo and hope to collect interesting data

**Comment by wwylele** [comment]
Updated monster name mapping. Still need to figure out the name for small monsters

**Comment by PatrickSR** [comment]
Can I share these contents to my app?

**Comment by wwylele** [comment]
@PatrickSR Yes you can. I also updated the README for clarification. btw, do you have your app project online? I am just curious as I also thought about making an android app or something.

**Comment by PatrickSR** [comment]
Actually I developed an app called "mini program" on WeChat to provide to Chinese players.I also developed the MHGU database "mini program".I can share with you if you have a WeChat account

**Comment by LITTOMA** [comment]
So... You guys are both Chinese...

**Comment by PatrickSR** [comment]
😱 OMG

**Comment by wwylele** [comment]
噗
微信的话就算了，我的微信是只用来和亲人联系的。

**Comment by PatrickSR** [comment]
方便给我一个联系方式吗？有问题可以请教

**Comment by wwylele** [comment]
请用我的邮箱wwylele@gmail.com联系我。如果是很短的问题，可以用QQ 2992393805
