### ISSUE TITLE
Update suffix version

### ISSUE THREAD

**Issue by dtlnor** [wwylele/mhrice#11]
the following suffix verison was updated in the Latest version of mhrise
(the commented one is the old version number)
```   m.insert("sdf", 0x77da5e9d); //0x77a4cbdd
    m.insert("mmtr", 0x77da5e9d); //0x77a4cbdd
    m.insert("mmtrs", 0x77da5e9d); //0x77a4cbdd
    m.insert("vsdf", 0x77da5e9e); //0x77a4cbde

**Comment by wwylele** [comment]
I added them in https://github.com/wwylele/mhrice/commit/8a162889ef22096628198a829308936295c62835 . Do you happen to know if other file format has updated suffix version?

**Comment by dtlnor** [comment]
ah, `sdf` also updated:
`m.insert("sdf", &[0x77da5e9d, 0x77a4cbdd]);`
so far only these four file format has updated which presented in pak file. For the file format doesn't present in pak file I don't know how to verify it.

**Comment by dtlnor** [comment]
I'm sorry that maybe there are some mistake when I doing research. The version I provided is not up-to-date(3.4.1). 
For `sdf`, `mmtr`, `mmtrs` it should be `0x77de5a9e`, and for `vsdf` it should be `0x77de5a9f`
```
    m.insert("sdf", &[0x77de5a9e, 0x77da5e9d, 0x77a4cbdd]);
    m.insert("mmtr", &[0x77de5a9e, 0x77da5e9d, 0x77a4cbdd]);
    m.insert("mmtrs", &[0x77de5a9e, 0x77da5e9d, 0x77a4cbdd]);
    m.insert("vsdf", &[0x77de5a9f, 0x77da5e9e, 0x77a4cbde]);
```

**Comment by wwylele** [comment]
Closing this as the current list has been updated to match the PC version.
