### ISSUE TITLE
[tdb-dump]missing closing bracket on return attribute

### ISSUE THREAD

**Issue by dtlnor** [wwylele/mhrice#14]
in the tdb output of PC 3.6.1.1 version
in class `snow.AgapanthusClient.<>c`
in method ```System.ValueTuple`2<System.String,snow.AgapanthusClient.FileInfoData> <onReceiveInfo>b__35_0```

the return attribute is missing the closing bracket

`line 1267060~`
```
    /* returns */[System.Runtime.CompilerServices.TupleElementNamesAttribute(["f","u",]
    /*16896, 0*/ [hid_by_sig]internal  System.ValueTuple`2<System.String,snow.AgapanthusClient.FileInfoData> <onReceiveInfo>b__35_0 (
        /*0*/  snow.AgapanthusClient.FileInfoData u,
        /*0*/  System.String f,
    );
```

I've tried to change the code of `tdb.rs` on `line 959`
`print!("]");` to `print!("])]");` 
which seems fine to solve this problem as far as I can see

**Comment by wwylele** [comment]
oops. Thanks for the report!

**Comment by wwylele** [comment]
Should be fixed in https://github.com/wwylele/mhrice/commit/8fce9d88aad78c623134f5c20e19399bf5daa257
