### ISSUE TITLE
read-tdb error with sunbreak demo.

### ISSUE THREAD

**Issue by chetuna** [wwylele/mhrice#21]
I got an error when running read-tdb on Sunbreak demo.

`command: mhrice read-tdb -t "F:\SteamLibrary\steamapps\common\MONSTER HUNTER RISE SUNBREAK DEMO\MHRiseSunbreakDemo.exe" > tdb.cs`
`Error: failed to fill whole buffer`

Is there a solution?

- Win10 (x64)
- cargo 1.61.0 (a028ae42f 2022-04-29)
- rustc 1.61.0 (fe5b13d68 2022-05-18)
- rustup 1.24.3 (ce5817a94 2021-05-31)

**Comment by wwylele** [comment]
The new sunbreak demo doesn't seem to have clear text tdb in the exe file. Instead, you need to dump a full minidump from a running game, and use the `read-dmp-tdb` command

**Comment by chetuna** [comment]
I could not handle the dmp command well because I was not sure about the map option and address.
I will wait for the release of sunbreak.  Thanks for this great project.

**Comment by wwylele** [comment]
You can just leave the map and address away. They are optional. `--map` is an output file to generate function address mapping. `--address` is to provide the TDB address if you know it in advance, to skip the slow scanning.

**Comment by wwylele** [comment]
I am going to close this as wont-fix, as I am not interested in dis-obfuscate the exe
