### ISSUE TITLE
Error in read-tdb ’failed to fill whole buffer’.

### ISSUE THREAD

**Issue by chetuna** [wwylele/mhrice#45]
I don't know which version this is happening from, but now I get an error when I use the read-tdb command. It used to be usable.

`read-tdb -t MonsterHunterRise.exe
Error: failed to fill whole buffer`

This can be predicted to be due to the fact that _TDB_ANCHOR_ is now not accurate and is beyond its end position.
Thanks for the long-term development.

**Comment by wwylele** [comment]
Since the game 10.0 update (I think?), the exe is obfuscated and no longer support direct TDB dumping. You can however do the following:
 - Run the game 
 - Create a full dump as a minidump *.dmp file (ProcessExplorer can do this)
 - Run `mhrice read-dmp-tdb --dmp <path-to-dmp-file> [options...]`

**Comment by chetuna** [comment]
I see, there was a change in the game file itself.
We have confirmed that the _read-dmp-tdb_ command dumps well. Thank you so much.
