### ISSUE TITLE
NPC Textures

### ISSUE THREAD

**Issue by Silvris** [wwylele/mhrice#5]
NPC textures seem to have some weirdness to them. I've been looking into them separately from this repo, and both my attempts and this repo fail to properly extract the ALBD of most NPCs. Here's the output from "natives/NSW/npc/npc002_00/npc002_00_body/npc002_00_body_ALBD.tex.28". Is there data missing within the file itself, or is it potentially compressed?
![hinoaTex](https://user-images.githubusercontent.com/58583688/112702068-52ace800-8e60-11eb-83ca-190518322edc.png)

**Comment by wwylele** [comment]
Looks like there is some tiling error. I'll look into it

**Comment by wwylele** [comment]
Thanks for the report! I pushed a potential fix in https://github.com/wwylele/mhrice/commit/87f9816b54a6c967ea1c6c2d3e2c3698bf19be31 . Could you help me test to see if work for other textures and doesn't break anything?

**Comment by Silvris** [comment]
It looks like it's working for npcs, but is now causing added failures on monster textures (which were already working). Is it possible there's something in the file that might flag this? I'm suspicious of 0x21 in the header, as I found 0x20 to be generally close to the value of (super_height = 2**n) where n is the value at that address.

**Comment by Silvris** [comment]
In the NPC textures, 0x21 is at a value of 4, while almost every other texture has it at 0.

**Comment by wwylele** [comment]
Thanks for the report and investigation! I agree with your theory. I pushed another fix in https://github.com/wwylele/mhrice/commit/68a85535ddee2798c6f167ee0c6d1795d786826b
