### ISSUE TITLE
building weapon tree from json download

### ISSUE THREAD

**Issue by skwallace36** [wwylele/mhrice#52]
is there a way to build the weapon tree from the json on mhrice? I am struggling to figure this out exactly - just interested in building a UX for weapon trees similar to your website

**Comment by wwylele** [comment]
Yes, there is a way. The precise logic is here: https://github.com/wwylele/mhrice/blob/main/src/extract/gen_pedia.rs#L2966, but to put it in words:
 
Each weapon has a "tree"/"param" array in json. Each elements in this array represents a weapon and its position in the tree:
 - weapon_id: The ID of the weapon
 - tree_type: the ID of the "tree" / row in the weapon tree graph (e.g. "Defender Weapon Tree", "Kamura Tree" etc. but in numbers)
 - index: the column in the weapon tree graph
 - next_weapon_type_list / next_weapon_index_list: positions of the next upgrades. Again, weapon_type is the row, and weapon_index is the column. 
 - prev_weapon_type / prev_weapon_index: the position of the weapon before upgrading this this weapon

With these alone, you can assemble a weapon tree graph. Then you use other information in json to attach names, attack values and so on to each position using the weapon ID.

**Comment by skwallace36** [comment]
thank you so much for your response! I will give it a shot and let you know. I honestly think the json is so huge I was just struggling with getting a good picture of it. 

was just able to plop your json into https://github.com/glideapps/quicktype and it worked very well... let's see how this goes
