### ISSUE TITLE
Support drop_item_info_data

### ISSUE THREAD

**Issue by d3vdev** [wwylele/mhrice#8]
I guess "enemy/em{0:03}/{1:02}/user_data/em{0:03}_{1:02}_drop_item_info_data.user" this file include drop information of monster

I tried to parse this file. but i can't understand rsz_struct,

so could you implement this function or let me know some information rsz files and more detail code for extracting rsz?

**Comment by d3vdev** [comment]
and i met this error 

```
$ cargo run --release -- gen-json --pak re_chunk_000.pak*
   Compiling mhrice v0.1.0 (/mhrice)
    Finished release [optimized] target(s) in 31.29s
     Running `target/release/mhrice gen-json --pak re_chunk_000.pak re_chunk_000.pak.patch_001.pak re_chunk_000.pak.patch_002.pak`
Error: Generating large monsters

Caused by:
    0: drop_item
    1: Unsupported type 615100A6
```

**Comment by wwylele** [comment]
I'll get there when I have time. If you can't wait, you could try following this guide: https://github.com/wwylele/mhrice/wiki/RSZ to add support for this file

**Comment by wwylele** [comment]
FIxed in https://github.com/wwylele/mhrice/commit/3ea2d8b876066984cc6cdb7a4902c1482b27c9ab
