### ISSUE TITLE
Pre-emptive TDB fix

### ISSUE THREAD

**Issue by Silvris** [wwylele/mhrice#9]
Was looking at the tdb for the RE8 demo that came out on PC, and it uses version 0x45. One thing I noticed though is that in the fields, several of the name offsets would be way higher than the file allowed, so I changed line 557 (of the old code supporting version 0x45) to `let (name_offset,unkn2) = file.read_u32()?.bit_split((22,10));` and it seems to have worked. It might not be important now for MHRise, but given that the two formats are rather close otherwise, it may be useful to know later.

**Comment by Silvris** [comment]
Just letting you know that this is now relevant with the release of Sunbreak's demo.

**Comment by wwylele** [comment]
I pushed https://github.com/wwylele/mhrice/commit/093553ea77ddea778d28b10ceeb24567f73d5ea4 for sunbreak fix but I don't remember where the original code was... is this the `read_string` fix?
